### ISSUE TITLE
Navigatie/header

### ISSUE THREAD

**Issue by latoyaln** [Seijno/wogo#15]

**Comment by Seijno** [comment]
## Conclusie
Deze issue is al opgelost in pull request #29 Hierbij was het grootste werkdeel in de mobile versie gebeurd, ook tijdens het werken aan #30 heb ik de giftcard pagina in de header kunnen koppelen met contentfull. Dit werkt dus.

- [x] Navigatie waarbij je kan navigeren naar verschillende paginas
